### PR TITLE
LSC Controller now works properly with EU Detector Cover

### PR DESCRIPTION
**Pull request by matt-159**

### CODE REVIEW

**Comment by Prometheus0000** [comment]
Uh, you did see the other PR, right? Though I don't think it'll be too hard to merge when I finish.

**Comment by matt-159** [comment]
i mean this only really adds a couple lines to end of the end of:
src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java

**Comment by matt-159** [comment]
@Prometheus0000 you need to update your .gitignore file to exclude the unnecessary stuff in your repository

**Comment by Prometheus0000** [comment]
Given how much stuff you changed not in the normal dirs, I'm just going to delete and re-clone the whole thing after I finish my PR. I probably won't finish today, so it's better to merge yours first.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
