### PR TITLE
Big LSC lol

### PR DESCRIPTION
**Pull request by POPlol333**
I don't want GD or Sampsa to be able to fullfil a max size LSC so I made it bigger
image

### CODE REVIEW

**Review by MadMan310 — APPROVED** [review]

**Comment by POPlol333** [comment]
as a real argument that I obviously worked on before making this.. this make LSC more relevant and competitive against the gtpp thingy I don't remember the name for mid tier

**Comment by Dream-Master** [comment]
GT++ recipes sucks. Radox cell need a propper rework

**Comment by POPlol333** [comment]
this one is not gtpp just saying..

**Comment by Alrightsc** [comment]
GT++ PSS is not great vs LSC since buffs is what Dream is saying. It needs more love too (though I don't think anyone wants to build a brown looking poop box).

**Comment by POPlol333** [comment]
the brown looking poop box actually store more energy every tier except the last one because it doesn't have capacitor for it lol

**Comment by Alrightsc** [comment]
Actually no, PSS EV only stores a bit more EU than LSC EV, then after that LSC capacitors just stomp PSS every tier, since PSS scales at 4x vs. LSC x10. I am not sure about the max height of PSS you can build though, probably similar to LSC (which in that case it's hardly competitive at all).

**Comment by POPlol333** [comment]
? has something changed ? I remember doing the PSS in 2.2.0.0 because boubou told me it was sadly outstanding LSC by a lot

**Comment by Dream-Master** [comment]
> this one is not gtpp just saying..

Ik but that remember me gt++ need a rework this half finished casing bs need to be finished or changed to a gt casing

**Review by boubou19 — APPROVED** [review]

**Comment by boubou19** [comment]
looks like now there is a goal bigger than the stargate to reach lmao

**Comment by Elisis** [comment]
> looks like now there is a goal bigger than the stargate to reach lmao

Obviously that just means we need to nerf stargate more :trollface:

**Comment by Dream-Master** [comment]
@GTNH-Colen nerf Stargate NOW!
:trollface:

**Pull request merged**
