### PR TITLE
fix getTankInfo not geting the fluids

### PR DESCRIPTION
**Pull request by botn365**
fix stuff like OC and fluid storage bus not being able to read fluids from the multi hatch

### CODE REVIEW

**Review by leagris — APPROVED** [review]
Looks ok

**Comment by Prometheus0000** [comment]
Does this fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6447 then?

**Comment by Dream-Master** [comment]
@botn365

**Comment by botn365** [comment]
i think it does

**Pull request merged**
