### PR TITLE
Change UV glass laser hatch limitation to LuV

### PR DESCRIPTION
**Pull request by Elisis**
Improves parity between PSS and LSC

### CODE REVIEW

**Review by Connor-Colenso — CHANGES_REQUESTED** [review]
I would far rather you make the PSS require the MAX tier storage for lasers than buff the LSC here.

**Comment by GTNHAfx237v7** [comment]
I’m with Colen on this one and prefer an additional challenge to the PSS instead of a buff to the LSC.

**Comment by Elisis** [comment]
Is it that much of a buff when lasers are already gated so heavily?

**Comment by alexandre-tardif** [comment]
This allows the use of low power laser on the LSC before UV glass. They're not used much but there's that to consider.

**Comment by Elisis** [comment]
So this is buffing low power lasers, therefore giving them more use? That isn't necessarily a bad thing.

**Comment by alexandre-tardif** [comment]
Yea that's my point. I don't think many people will use them but I mean they'd actually be usable

**Comment by GTNHAfx237v7** [comment]
In all fairness, you cannot use TT lasers without active transformers which are ZPM level, so there is already a noticeable gating here. However when you are ZPM level making the UV glass is not a big deal either.

**Comment by Elisis** [comment]
I just thought it was kind of a strange restriction in general to have next to PSS which doesn't impose such

**Comment by alexandre-tardif** [comment]
In my opinion with the new Borosilicate recipe making UV glass is pretty cheap now and wasn't much of a gate already, also making vacuum pipe is UV so it's still gated to at least ZPM with the ++ assembler

**Comment by Connor-Colenso** [comment]
I'm not really sure why you want more people to use lasers when lasers are in desperate need of a rebalance as is.

**Comment by boubou19** [comment]
Yeah lasers need a whole balance rework. We may want to do this during the rebalance process instead of randomly doing it here and there, so we have a better overview of what's going on.

**Pull request closed without merging**
