### PR TITLE
TFFT recipes

### PR DESCRIPTION
**Pull request by DianeXD**
TFFT Controller:
tfftcontroller
TFFT Casing:
tfftcasing
TFFT Multi Hatch:
tffthatch
T1(LV):
tfftfield1
T2(MV):
tfftfield2
T3(HV):
tfftfield3
T4(EV):
tfftfield4
T5(IV):
tfftfield5
T6(LuV):
tfftfield6
T7(UV):
tfftfield7
T8(UEV):
tfftfield8
T9(UMV):
tfftfield9
T10(UXV):
tfftfield10

Here is the specific data of the storage blocks
https://github.com/GTNewHorizons/KekzTech/blob/master/src/main/java/common/tileentities/GTMTE_TFFT.java#L49-L60

### CODE REVIEW

**Comment by Connor-Colenso** [comment]
Why totem of undying (or w/e knock off version we have of it)?

Also no more fluid cores?

**Review by Dream-Master — APPROVED** [review]

**Comment by Dream-Master** [comment]
we can change recipes in a second pr if some need adjustments

**Comment by DianeXD** [comment]
> Why totem of undying (or w/e knock off version we have of it)?

The cost of t10 is 0, basically just give it a random battery or something, tfft also uses a lot of eio materials, I guess totemic capacitor is interesting.

**Comment by Elisis** [comment]
Adding totem of undying seems kinda tacky to me, especially as it'll probably just become yet another single-user item™️

**Comment by DianeXD** [comment]
Just to clarify, we don't have totem of undying, it's a capacitor from eio

**Pull request merged**
